# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [ ]:
import numpy as np

2. Create a null vector of size 10 

In [3]:
import numpy as np
w=np.zeros((10,10))
w

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

3. Create a vector with values ranging from 10 to 49

In [4]:
x=np.arange(10, 50)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [5]:
x.shape

(40,)

5. Print the type of the previous array in question 3

In [6]:
x.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [2]:
import numpy as np
print(np.__version__)
print(np.show_config())

1.18.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/ProgramData/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\

7. Print the dimension of the array in question 3


In [8]:
x.ndim

1

8. Create a boolean array with all the True values

In [2]:
import numpy as np
np.ones((2, 2), dtype=bool)
    

array([[ True,  True],
       [ True,  True]])

9. Create a two dimensional array




In [7]:
import numpy as np
arr2d=np.array([[1,2,3],[4,5,6]])
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

10. Create a three dimensional array



In [8]:
import numpy as np
arr3d=np.array([[[1,2,3],[4,5,6], [7,8,9]]])
arr3d

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [1]:
import numpy as np
x = np.arange(1, 10)
print("Original array:")
print(x)
print("Reverse array:")
x = x[::-1]
print(x)

Original array:
[1 2 3 4 5 6 7 8 9]
Reverse array:
[9 8 7 6 5 4 3 2 1]


12. Create a null vector of size 10 but the fifth value which is 1 

In [6]:
import numpy as np
x=np.zeros(10)
x[4]=1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [9]:
import numpy as np
array_2D=np.identity(3)
print('3x3 matrix:')
print(array_2D)

3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [12]:
arr = np.array([1, 2, 3, 4, 5.0])
arr.dtype

dtype('float64')

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [14]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
w=arr1*arr2
w

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [18]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])
arr1==arr2

array([[False, False, False],
       [False, False, False]])

17. Extract all odd numbers from arr with values(0-9)

In [23]:
x=np.arange(1,10,2)
x

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [114]:
x=np.arange(1,10,2)
x[0:5]=-1
x

array([-1, -1, -1, -1, -1])

19. arr = np.arange(10)

Replace the values of indexes 5,6,7 and 8 to **12**

In [33]:
arr = np.arange(10)
arr[5:9]='12'
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [15]:
import numpy as np
x = np.ones((5,5))
print("Original array:")
print(x)
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)

Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [30]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])

arr2d[1][1]='12'
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [36]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0]='64'
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [45]:
arr=np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])

print(arr[0])

[0 1 2 3 4]


24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [51]:
arr=np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
print(arr[1][1])

6


25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [60]:
arr=np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
arr
print(arr[0:2, 2])

[2 7]


26. Create a 10x10 array with random values and find the minimum and maximum values

In [66]:
array1 = np.arange(100).reshape(10,10)
array1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [72]:
np.min(array1), np.max(array1)

(0, 99)

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [73]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a, b))

[2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [74]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(np.in1d(a, b))[0]

array([1, 3, 5, 7], dtype=int64)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [83]:
x= names != 'Will'
x

array([ True,  True, False,  True, False,  True,  True])

In [85]:
data[~(names == 'Will')]

array([[-0.07829636,  0.16469616,  0.91004864,  1.63987266],
       [ 0.58476489,  0.08496026, -1.79630448, -0.7625233 ],
       [-0.58693032, -2.65204272,  1.16415578, -1.38897797],
       [ 0.18897981,  0.40797507,  1.28029622, -1.34961777],
       [-0.25630845, -0.24527438, -0.93402958, -0.67734449]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [79]:
w = (names == 'Joe') | (names == 'Will')
w


array([False,  True,  True, False,  True,  True,  True])

In [81]:
data[w]

array([[ 0.58476489,  0.08496026, -1.79630448, -0.7625233 ],
       [-0.96971582,  1.0536577 , -1.17502829,  0.27933023],
       [-0.24364215, -0.76358843, -1.3347589 , -0.08722909],
       [ 0.18897981,  0.40797507,  1.28029622, -1.34961777],
       [-0.25630845, -0.24527438, -0.93402958, -0.67734449]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [77]:
array1 = np.arange(15.0).reshape(5,3)
array1

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [78]:
array1 = np.arange(16.0).reshape(2,2,4)
array1

array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.]],

       [[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]]])

33. Swap axes of the array you created in Question 32

In [91]:
a = np.arange(16.0).reshape(2,2,4)
np.swapaxes(a,0,2)

array([[[ 0.,  8.],
        [ 4., 12.]],

       [[ 1.,  9.],
        [ 5., 13.]],

       [[ 2., 10.],
        [ 6., 14.]],

       [[ 3., 11.],
        [ 7., 15.]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [93]:
a= np.arange(10)
x=np.sqrt(a)
x

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [104]:
a= np.arange(10)
x=np.sqrt(a)
x[x < .5] = 0
print(x)

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [106]:
a=np.random.randn(12)
print(a)
b=np.random.randn(12)
print(b)

[ 0.36187047 -0.3882557  -0.83534732 -0.01704521  0.82168988  1.43939642
 -0.85743211 -1.4730399  -0.26468082 -1.65743914  0.51570414  0.1166196 ]
[-6.98125770e-01 -2.07477251e-01 -9.74016231e-02 -2.04616278e+00
 -4.31437957e-01  1.48762946e+00 -9.48880110e-04 -4.60627703e-01
  1.00754529e+00  1.04290959e+00 -1.17625387e-01 -7.83565954e-01]


In [107]:
maxi=np.maximum(a,b)
maxi

array([ 3.61870473e-01, -2.07477251e-01, -9.74016231e-02, -1.70452099e-02,
        8.21689878e-01,  1.48762946e+00, -9.48880110e-04, -4.60627703e-01,
        1.00754529e+00,  1.04290959e+00,  5.15704138e-01,  1.16619598e-01])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [108]:
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [49]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
result = np.setdiff1d(a, b)
print(result)

[1 2 3 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [109]:
import numpy

print("Printing Original array")
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 
print (sampleArray)

print("Array after deleting column 2 on axis 1")
sampleArray = numpy.delete(sampleArray , 1, axis = 1) 
print (sampleArray)

arr = numpy.array([[10,10,10]])

print("Array after inserting column 2 on axis 1")
sampleArray = numpy.insert(sampleArray , 1, arr, axis = 1) 
print (sampleArray)

Printing Original array
[[34 43 73]
 [82 22 12]
 [53 94 66]]
Array after deleting column 2 on axis 1
[[34 73]
 [82 12]
 [53 66]]
Array after inserting column 2 on axis 1
[[34 10 73]
 [82 10 12]
 [53 10 66]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [12]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
print(np.dot(x, y))

[[ 28.  64.]
 [ 67. 181.]]


40. Generate a matrix of 20 random values and find its cumulative sum

In [22]:
a=np.random.randn(20)
a

array([-0.16513071,  0.29940332,  1.36875472, -1.04578922, -0.51991191,
       -1.73283921, -0.07987109, -1.06433436, -0.36223586, -1.14207149,
        0.47278743, -0.35755665, -1.17283759,  1.09331566, -0.16100485,
        0.8700059 ,  2.53835263,  0.49159764,  0.24671086, -0.82111662])

In [23]:
b=np.cumsum(a)
b

array([-0.16513071,  0.1342726 ,  1.50302733,  0.4572381 , -0.06267381,
       -1.79551302, -1.87538411, -2.93971847, -3.30195433, -4.44402583,
       -3.97123839, -4.32879504, -5.50163263, -4.40831697, -4.56932182,
       -3.69931592, -1.16096329, -0.66936564, -0.42265478, -1.24377139])